export const articles = [
  {
    id: 1,
    title: "Seenaa_Fiqiruu",
    description: "Our guest today on Gammadaa Show is a talented and wonderful girl, #Seenaa_Fiqiruu🙏📌. The story of the songs of many of our artists is going to be heard again in a wonderful way with her kilole voice. We’ll be back at 3:15pm on Etv and our YouTube channel, and you’ll love it even more. Our program sponsor: Cooperative Bank of Orissa, Ethio Telecom, Mijuu Coffee.",
    image: "/photo3.jpg",
    category: "talented",
    color: "bg-purple-500 text-blue-800",
    author: {
      name: "Gammada show",
      avatar: "",
    },
    date: "5 days ago",
    link: "#",
  },
  {
    id: 2,
    title: "Senet_Gizachew",
    description: "Here is the Guest you were predicting yesterday has come true. We called the talented and Common student #Senet_Gizachew and Pro #Gemechis_Desta_Buba and wished them success. There are many #surprises in this program and you will benefit from many educational programs. Thank you for letting us know in various ways that Gammadaa Show is your chosen program🙏🥊",
    image: "/photo2.jpg",
    category: "success",
    color: "bg-green-100 text-green-800",
    author: {
      name: "Gammada show",
      avatar: "",
    },
    date: "10 days ago",
    link: "#",
  },
  {
    id: 3,
    title: "Seenaa_Fiqiruu",
    description: "Our guest today on Gammadaa Show is a talented and wonderful girl, #Seenaa_Fiqiruu🙏📌. The story of the songs of many of our artists is going to be heard again in a wonderful way with her kilole voice. We’ll be back at 3:15pm on Etv and our YouTube channel, and you’ll love it even more. Our program sponsor: Cooperative Bank of Orissa, Ethio Telecom, Mijuu Coffee.",
    image: "/photo3.jpg",
    category: "talented",
    color: "bg-purple-500 text-blue-800",
    author: {
      name: "Gammada show",
      avatar: "",
    },
    date: "5 days ago",
    link: "#",
  },
  {
    id: 4,
    title: "Introducing Gammada Show's Afan Oromo Podcast",
    description: "Join us for an exciting episode of Gammada Show, where we dive into the world of Afan Oromo podcasts. This episode features interesting discussions, and great insights for the future.",
    image: "/Gammada.jpg",
    category: "Podcast",
    date: "1 day ago",
    author: {
      name: "Gammada Show",
      avatar: "",
    },
    link: "#",
    isFeatured: true,
  },
];
