// data.ts

export const articles = [
    {
      id: 1,
      title: "Mastering Tailwind CSS",
      description: "A guide to using Tailwind CSS for rapid UI development.",
      image: "/photo3.jpg",
      category: "Design",
      color: "bg-purple-500 text-blue-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "5 days ago",
      link: "#",
    },
    {
      id: 2,
      title: "Introduction to Next.js",
      description: "Learn the basics of building web apps with Next.js.",
      image: "/photo2.jpg",
      category: "JavaScript",
      color: "bg-green-100 text-green-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "10 days ago",
      link: "#",
    },
    {
      id: 3,
      title: "React State Management",
      description: "Manage complex state efficiently using modern React patterns.",
      image: "/photo1.jpg",
      category: "React",
      color: "bg-blue-100 text-blue-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "7 days ago",
      link: "#",
    },
    {
      id: 4,
      title: "Full-Stack Development Guide",
      description: "Combine frontend and backend for scalable applications.",
      image: "/Gammada.jpg",
      category: "Full-Stack",
      color: "bg-red-100 text-red-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "2 days ago",
      link: "#",
      isFeatured: true, // Mark one article as featured
    },
  ];


export const articlespopular = [
    {
      id: 1,
      title: "Mastering Tailwind CSS",
      description: "A guide to using Tailwind CSS for rapid UI development.",
      image: "/photo9.jpg",
      category: "Design",
      color: "bg-purple-500 text-blue-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "5 days ago",
      link: "#",
    },
    {
      id: 2,
      title: "Introduction to Next.js",
      description: "Learn the basics of building web apps with Next.js.",
      image: "/photo8.jpg",
      category: "JavaScript",
      color: "bg-green-100 text-green-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "10 days ago",
      link: "#",
    },
    {
      id: 3,
      title: "React State Management",
      description: "Manage complex state efficiently using modern React patterns.",
      image: "/photo7.jpg",
      category: "React",
      color: "bg-blue-100 text-blue-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "7 days ago",
      link: "#",
    },
    {
      id: 4,
      title: "Full-Stack Development Guide",
      description: "Combine frontend and backend for scalable applications.",
      image: "/Gammada.jpg",
      category: "Full-Stack",
      color: "bg-red-100 text-red-800",
      author: {
        name: "Gammada show",
        avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
      },
      date: "2 days ago",
      link: "#",
    },
    {
        id: 5,
        title: "Introduction to Next.js",
        description: "Learn the basics of building web apps with Next.js.",
        image: "/photo6.jpg",
        category: "JavaScript",
        color: "bg-green-100 text-green-800",
        author: {
          name: "Gammada show",
          avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
        },
        date: "10 days ago",
        link: "#",
      },
      {
        id: 6,
        title: "React State Management",
        description: "Manage complex state efficiently using modern React patterns.",
        image: "/photo5.jpg",
        category: "React",
        color: "bg-blue-100 text-blue-800",
        author: {
          name: "Gammada show",
          avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
        },
        date: "7 days ago",
        link: "#",
      },
      {
        id: 7,
        title: "Mastering Tailwind CSS",
        description: "A guide to using Tailwind CSS for rapid UI development.",
        image: "/photo4.jpg",
        category: "Design",
        color: "bg-purple-500 text-blue-800",
        author: {
          name: "Gammada show",
          avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
        },
        date: "5 days ago",
        link: "#",
      },
      {
        id: 8,
        title: "Introduction to Next.js",
        description: "Learn the basics of building web apps with Next.js.",
        image: "/photo3.jpg",
        category: "JavaScript",
        color: "bg-green-100 text-green-800",
        author: {
          name: "Gammada show",
          avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
        },
        date: "10 days ago",
        link: "#",
      },
      {
        id: 9,
        title: "Introduction to Next.js",
        description: "Learn the basics of building web apps with Next.js.",
        image: "/photo2.jpg",
        category: "JavaScript",
        color: "bg-green-100 text-green-800",
        author: {
          name: "Gammada show",
          avatar: "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/jese-leos.png",
        },
        date: "10 days ago",
        link: "#",
      },
  ];
  